# Generated by Django 4.0.3 on 2022-04-06 22:03

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('agency', 'Agency'), ('digital', 'Digital'), ('creative', 'Creative')], default='creative', max_length=128)),
                ('featured_image', versatileimagefield.fields.VersatileImageField(upload_to='')),
                ('description', models.TextField()),
                ('image_one', versatileimagefield.fields.VersatileImageField(upload_to='')),
                ('image_two', versatileimagefield.fields.VersatileImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=128)),
                ('project_details', models.TextField()),
            ],
        ),
    ]
