# Generated by Django 4.0.3 on 2022-04-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
