# Generated by Django 4.0.3 on 2022-04-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_blog_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
