# Generated by Django 4.0.3 on 2022-04-13 08:58

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_img',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
