# Generated by Django 4.0.3 on 2022-04-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_slider_slider_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
    ]
