# Generated by Django 4.0.3 on 2022-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
