# Generated by Django 4.0.3 on 2022-04-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_project_details_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_categorys', to='web.project')),
            ],
        ),
    ]
