# Generated by Django 4.0.3 on 2022-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_contact_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
